#!/bin/bash
#SBATCH -J nf-S-r1
#SBATCH -p stajichlab
#SBATCH -c 1
#SBATCH --mem=8G
#SBATCH -t 30-00:00:00
#SBATCH -o /S/.nf_launch/r1/slurm-%j.out
#SBATCH -e /S/.nf_launch/r1/slurm-%j.err
#
# Generated by `bin/ni pangenome run` -- do not edit; rerun that command instead.
# Study: /S   Run: r1   Pipeline: stajichlab/NovInvenio @ 0dddb421720e0eb0a3045231608b27b113d49be6
set -uo pipefail
export PATH="$HOME/.pixi/bin:$HOME/.local/bin:$PATH"
module load java 2>/dev/null || true
cd /S/.nf_launch/r1
rc=0
nextflow run stajichlab/NovInvenio -r 0dddb421720e0eb0a3045231608b27b113d49be6 -main-script pangenome.nf \
    -params-file /S/.nf_launch/r1/params.yaml \
    -profile slurm \
    -c /A/clones/0dddb421720e0eb0a3045231608b27b113d49be6/conf/ucr_hpcc_slurm.config \
    -c /S/queue.config \
    -with-trace /S/results/r1/trace.txt \
    -resume || rc=$?
/usr/bin/python3.12 -c "import sys; sys.path.insert(0, '/N/lib'); from ni_pangenome import record_exit; record_exit('/S/.nf_launch/r1/ni_run.json', $rc)"
if [ "$rc" -eq 0 ]; then
    /usr/bin/python3.12 /N/bin/ni pangenome stage --study-dir /S --run r1 || rc=$?
fi
exit $rc
