#!/usr/bin/bash
# Issue #132 gap (a): run one tier-1 clustering grid point of the
# genus_vs_ureesii study (529 Coccidioides strains + outgroup) through the
# full pangenome.nf chain, so every grid point gets islands, trans pairs,
# Leiden modules and the assembly-quality partial rho.
#
# Usage:
#   studies/fungi/coccidioides_pangenome/run_tier1_sweep.sh <min_id> <cov> [--dry-run] [extra nextflow args...]
#   e.g. run_tier1_sweep.sh 0.8 0.5
#
# What it does:
#   - writes <launch_dir>/submit_nextflow_head.sh and submits it with sbatch
#     (the Nextflow head job runs on the stajichlab partition);
#   - one launch dir per point: .nf_launch/tier1_sweep_id<min_id>_cov<cov>;
#   - outdir: results/tier1_sweep/ (outside the NovInvenio repo);
#   - project name: coccidioides_sweep_id<min_id>_cov<cov>. Passed as BOTH
#     --pangenome_project and --project: pangenome.nf's in-workflow
#     `params.project = params.pangenome_project` does not reach the
#     publishDir closures (earlier runs published to <outdir>/output/), so
#     without --project all sweep points would overwrite one another.
#
# Fixed choices for every point (like-for-like):
#   pangenome_rescue_enable = false  (rescue depends on clustering and costs
#       ~1,182 cpu-h per run; the baseline 0.9/0.8 point is also run
#       rescue-off). Set in .nf_launch/tier1_sweep_resources.config, NOT as a
#       CLI flag: Nextflow 26.04 keeps `--pangenome_rescue_enable false` as the
#       String "false", which is truthy, so rescue would still run.
#   --pangenome_island_pfam_hmm = a ONE-profile stub HMM. BUILD_ISLANDS only
#       runs when this param is set, but islands do not use Pfam output. The
#       full Pfam-A scan costs ~80 cpu-h per run at this scale. The stub keeps
#       BUILD_ISLANDS pipeline-native at near-zero Pfam cost. Pfam-derived
#       outputs of these runs (domain enrichment, module domains) are
#       therefore NOT meaningful and must not be used.
#
# Pipeline: a git-archive snapshot of NovInvenio at a fixed commit
# (.nf_launch/tier1_sweep_pipeline_<sha>/PIPELINE_COMMIT.txt), so live
# commits in the shared NovInvenio checkout cannot change a running sweep.
#
# All paths are absolute. No BASH_SOURCE use (SLURM-safe).

set -euo pipefail

MIN_ID="${1:?Usage: run_tier1_sweep.sh <min_id> <cov> [--dry-run] [extra nextflow args...]}"
COV="${2:?Usage: run_tier1_sweep.sh <min_id> <cov> [--dry-run] [extra nextflow args...]}"
shift 2
DRY_RUN=0
if [ "${1:-}" = "--dry-run" ]; then DRY_RUN=1; shift; fi
EXTRA_ARGS=("$@")

STUDY_DIR=/bigdata/stajichlab/jstajich/projects/NovInvenio_Investigations/studies/fungi/coccidioides_pangenome
PIPELINE_DIR="${NII_PIPELINE_DIR:-$STUDY_DIR/.nf_launch/tier1_sweep_pipeline_af6fd68}"
TAG="id${MIN_ID}_cov${COV}"
PROJECT="coccidioides_sweep_${TAG}"
OUTDIR="$STUDY_DIR/results/tier1_sweep"
LAUNCH_DIR="$STUDY_DIR/.nf_launch/tier1_sweep_${TAG}"
STUB_HMM="$OUTDIR/_inputs/single_profile_stub.hmm"
SWEEP_CONFIG="$STUDY_DIR/.nf_launch/tier1_sweep_resources.config"

for f in "$PIPELINE_DIR/pangenome.nf" "$STUB_HMM" "$SWEEP_CONFIG" \
         "$STUDY_DIR/config_genus_vs_ureesii.csv" "$STUDY_DIR/stajichlab_queue.config"; do
    [ -e "$f" ] || { echo "ERROR: missing $f" >&2; exit 1; }
done

if [ -f "$PIPELINE_DIR/PIPELINE_COMMIT.txt" ]; then
    COMMIT="$(cat "$PIPELINE_DIR/PIPELINE_COMMIT.txt")"
else
    COMMIT="$(git -C "$PIPELINE_DIR" rev-parse HEAD)"
fi

mkdir -p "$OUTDIR" "$LAUNCH_DIR"
echo "$COMMIT" > "$LAUNCH_DIR/pipeline_commit.txt"

# Quote extra args for embedding in the generated script.
EXTRA_QUOTED=""
for a in "${EXTRA_ARGS[@]+"${EXTRA_ARGS[@]}"}"; do EXTRA_QUOTED+=" $(printf '%q' "$a")"; done

HEAD_SCRIPT="$LAUNCH_DIR/submit_nextflow_head.sh"
cat > "$HEAD_SCRIPT" <<EOF
#!/bin/bash
#SBATCH -J nf-t1sweep-${TAG}
#SBATCH -p stajichlab
#SBATCH -c 1
#SBATCH --mem=6G
#SBATCH -t 3-00:00:00
#SBATCH -o $LAUNCH_DIR/slurm-%j.out
#SBATCH -e $LAUNCH_DIR/slurm-%j.err
# Generated by run_tier1_sweep.sh for min_id=${MIN_ID} cov=${COV}.
# Resubmit with: sbatch $HEAD_SCRIPT   (always -resume in this launch dir)
set -euo pipefail
export NXF_OPTS="-Xms1g -Xmx4g"
echo "== pipeline commit: $COMMIT (snapshot $PIPELINE_DIR) =="
cd "$LAUNCH_DIR"
nextflow run "$PIPELINE_DIR/pangenome.nf" \\
    --pangenome_samplesheet "$STUDY_DIR/config_genus_vs_ureesii.csv" \\
    --pangenome_data_dir "$STUDY_DIR/data_dir" \\
    --pangenome_cluster_backend mmseqs \\
    --pangenome_tier1_min_id ${MIN_ID} \\
    --pangenome_tier1_cov ${COV} \\
    --pangenome_project "$PROJECT" \\
    --project "$PROJECT" \\
    --outdir "$OUTDIR" \\
    --pangenome_island_pfam_hmm "$STUB_HMM" \\
    -profile slurm \\
    -c "$PIPELINE_DIR/conf/ucr_hpcc_slurm.config" \\
    -c "$STUDY_DIR/stajichlab_queue.config" \\
    -c "$SWEEP_CONFIG" \\
    -with-trace "$OUTDIR/$PROJECT/trace.txt" \\
    -resume${EXTRA_QUOTED}
EOF
chmod +x "$HEAD_SCRIPT"
mkdir -p "$OUTDIR/$PROJECT"

echo "launch dir: $LAUNCH_DIR"
echo "project:    $PROJECT"
echo "commit:     $COMMIT"
if [ "$DRY_RUN" -eq 1 ]; then
    echo "dry run: not submitting $HEAD_SCRIPT"
else
    sbatch "$HEAD_SCRIPT"
fi
